#!/usr/bin/env python3
"""Raster hoá font TrueType/OpenType thành file header bitmap font để nhúng vào SDK
cho DisplayTarget của FreeInkUI (FreeInkUIDisplayTarget.h).

Kết quả là font tỉ lệ 1 bit theo bố cục Adafruit-GFX: bitmap của mỗi glyph được
đóng gói MSB-first theo hàng, các bitmap nối liền thành một khối kèm bảng số đo
cho từng glyph. DisplayTarget vẽ được mọi BitmapFont có dạng này, nên có thể thay
Noto Sans đi kèm bằng mặt chữ của bạn.

Với --alpha, glyph được raster có khử răng cưa và lưu dưới dạng độ phủ 4 bit
(hai pixel mỗi byte, nửa byte cao trước, 0 = trong suốt, 15 = đậm hết;
BitmapFont::bpp == 4). DisplayTarget tái tạo độ phủ viền trên màn 1 bit bằng
cách dither Bayer có thứ tự - mượt hơn rõ rệt ở cỡ hiển thị (>= ~16px) với giá
là bộ nhớ flash gấp khoảng 4 lần dạng 1 bit.

Cách dùng:
    pip install pillow
    python3 gen_font.py --ttf MyFont.ttf --size 13 --name MyFont \\
        --out ../include/MyFontFont.h

Sau đó trong ứng dụng:
    #include <MyFontFont.h>
    target.setFont(freeink::ui::kMyFontFont);            // mọi slot
    target.setFont(theme.tokens.fontTitle, kMyFontFont); // một slot

Xem docs/freeink-ui.md ("Swapping the font") để có hướng dẫn đầy đủ.
"""
import argparse
import re
import sys

from PIL import Image, ImageDraw, ImageFont


def c_ident(name: str) -> str:
    ident = re.sub(r"[^0-9A-Za-z]", "", name)
    return ident or "Custom"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ttf", required=True, help="đường dẫn file .ttf/.otf cần raster")
    ap.add_argument("--size", type=int, default=13, help="cỡ pixel (mặc định 13)")
    ap.add_argument("--name", default="Custom", help="tên symbol, ví dụ NotoSans -> kNotoSansFont")
    ap.add_argument("--first", type=lambda v: int(v, 0), default=0x20)
    ap.add_argument("--last", type=lambda v: int(v, 0), default=0x7E)
    ap.add_argument("--alpha", action="store_true",
                    help="sinh glyph khử răng cưa 4 bit thay cho mask 1 bit")
    ap.add_argument("--out", required=True, help="đường dẫn file header đầu ra")
    args = ap.parse_args()

    sym = c_ident(args.name)
    font = ImageFont.truetype(args.ttf, args.size)
    ascent, descent = font.getmetrics()
    yadv = ascent + descent

    bitmap = bytearray()
    glyphs = []  # (cp, off, w, h, xadv, xoff, yoff)
    maxw = maxh = 0
    for cp in range(args.first, args.last + 1):
        ch = chr(cp)
        xadv = round(font.getlength(ch))
        bbox = font.getbbox(ch)
        off = len(bitmap)
        if off > 0xFFFF:
            sys.exit(f"lỗi: glyph U+{cp:04X} có offset bitmap {off} vượt kiểu uint16 của FontGlyph "
                     "bitmapOffset - hãy giảm --size hoặc thu hẹp khoảng --first/--last")
        if bbox is None or bbox[2] - bbox[0] <= 0 or bbox[3] - bbox[1] <= 0:
            glyphs.append((cp, off, 0, 0, xadv, 0, 0))
            continue
        l, t, r, b = bbox
        if args.alpha:
            # Rasterize anti-aliased and pack 4-bit coverage, two pixels per
            # byte, high nibble first (BitmapFont::bpp == 4).
            img = Image.new("L", (r + 2, b + 2), 0)
            ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=255)
            crop = img.crop((l, t, r, b))
            w, h = crop.size
            px = crop.load()
            acc = nnib = 0
            for y in range(h):
                for x in range(w):
                    acc = (acc << 4) | ((px[x, y] * 15 + 127) // 255)
                    nnib += 1
                    if nnib == 2:
                        bitmap.append(acc)
                        acc = nnib = 0
            if nnib:
                bitmap.append(acc << 4)
        else:
            img = Image.new("1", (r + 2, b + 2), 0)
            ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=1)
            crop = img.crop((l, t, r, b))
            w, h = crop.size
            px = crop.load()
            acc = nbits = 0
            for y in range(h):
                for x in range(w):
                    acc = (acc << 1) | (1 if px[x, y] else 0)
                    nbits += 1
                    if nbits == 8:
                        bitmap.append(acc)
                        acc = nbits = 0
            if nbits:
                bitmap.append(acc << (8 - nbits))
        glyphs.append((cp, off, w, h, xadv, l, t - ascent))
        maxw, maxh = max(maxw, w), max(maxh, h)

    out = []
    P = out.append
    P("#pragma once")
    P("")
    P("// AUTO-GENERATED by tools/gen_font.py - do not edit by hand.")
    P(f"// Source: {args.ttf} at {args.size}px. Covers U+{args.first:04X}..U+{args.last:04X}.")
    if args.alpha:
        P("// Glyph bitmaps are anti-aliased 4-bit coverage (two pixels per byte, high")
        P("// nibble first, 15 = full ink), row-major, concatenated; xOffset/yOffset")
        P("// are the upper-left corner relative to the pen origin on the baseline.")
    else:
        P("// Glyph bitmaps are 1bpp, MSB-first, row-major, concatenated; xOffset/yOffset")
        P("// are the upper-left corner relative to the pen origin on the baseline.")
    P("// Confirm the source font's license permits embedding rasterized bitmaps.")
    P("")
    P("#include <FreeInkUIFont.h>  // struct FontGlyph / BitmapFont")
    P("")
    P("namespace freeink {")
    P("namespace ui {")
    P("")
    P(f"inline constexpr uint8_t k{sym}Bitmap[] = {{")
    for i in range(0, len(bitmap), 16):
        P("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",")
    P("};")
    P("")
    P(f"inline constexpr FontGlyph k{sym}Glyphs[] = {{")
    for (cp, off, w, h, xadv, xoff, yoff) in glyphs:
        disp = "space" if cp == 0x20 else (f"0x{cp:02X}" if cp == 0x5C else chr(cp))
        P(f"    {{{off}, {w}, {h}, {xadv}, {xoff}, {yoff}}},  // '{disp}'")
    P("};")
    P("")
    P(f"inline constexpr BitmapFont k{sym}Font = {{")
    P(f"    k{sym}Bitmap, k{sym}Glyphs, 0x{args.first:04X}, 0x{args.last:04X}, "
      f"{yadv}, {ascent}, {maxw}, {maxh}, {4 if args.alpha else 1}}};")
    P("")
    P("}  // namespace ui")
    P("}  // namespace freeink")

    with open(args.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"đã ghi {args.out}: k{sym}Font  size={args.size}px bpp={4 if args.alpha else 1} "
          f"yAdvance={yadv} ascent={ascent} "
          f"glyphs={len(glyphs)} bitmap={len(bitmap)}B (~{len(bitmap) + len(glyphs) * 6}B flash)")


if __name__ == "__main__":
    main()
